import db from "./client.js";
import { createUser } from "./queries/users.js";
import { createItem } from "./queries/items.js";
import bcrypt from "bcrypt";
import dotenv from "dotenv";

dotenv.config();

await db.connect();
await seed();
console.log("🌱 Database seeded.");
await db.end();

async function seed() {
  const SALT_ROUNDS = 10;
  const hashedPassword = await bcrypt.hash("password123", SALT_ROUNDS);

  // === USERS ===
  const kyle = await createUser({
    name: "Kyle",
    email: "kyle@example.com",
    hashedPassword,
  });

  const mark = await createUser({
    name: "Mark",
    email: "mark@example.com",
    hashedPassword,
  });

  const john = await createUser({
    name: "John",
    email: "john@example.com",
    hashedPassword,
  });

  console.log("👤 Created users:", kyle.name, mark.name, john.name);

  // === KYLE’S CARDS (30 total, placeholders) ===
  const kyleCards = [
    // Football
    {
      title: "2020 Panini Prizm Patrick Mahomes Silver",
      category_id: 1,
      status_id: 2,
      player_name: "Patrick Mahomes",
      team_name: "Kansas City Chiefs",
      year: 2020,
      rookie: false,
      brand: "Panini Prizm",
      sub_brand: "Silver Refractor",
      tags: ["QB", "Chiefs", "Silver"],
      market_value: 1150,
      image_url: null,
    },
    {
      title: "2021 Panini Mosaic Tom Brady Touchdown Masters",
      category_id: 1,
      status_id: 1,
      player_name: "Tom Brady",
      team_name: "Tampa Bay Buccaneers",
      year: 2021,
      rookie: false,
      brand: "Panini Mosaic",
      sub_brand: "Insert",
      tags: ["Brady", "Insert", "Mosaic"],
      market_value: 45,
      image_url: null,
    },
    {
      title: "2023 Panini Select Joe Burrow Red Die-Cut",
      category_id: 1,
      status_id: 1,
      player_name: "Joe Burrow",
      team_name: "Cincinnati Bengals",
      year: 2023,
      rookie: false,
      brand: "Panini Select",
      sub_brand: "Red Die-Cut",
      tags: ["QB", "Bengals", "Select"],
      market_value: 85,
      image_url: null,
    },
    {
      title: "2020 Panini Prizm Justin Jefferson Rookie",
      category_id: 1,
      status_id: 2,
      player_name: "Justin Jefferson",
      team_name: "Minnesota Vikings",
      year: 2020,
      rookie: true,
      brand: "Panini Prizm",
      sub_brand: "Base",
      tags: ["Rookie", "Vikings"],
      market_value: 35,
      image_url: null,
    },
    {
      title: "2023 Donruss Brock Purdy Rated Rookie Retro",
      category_id: 1,
      status_id: 1,
      player_name: "Brock Purdy",
      team_name: "San Francisco 49ers",
      year: 2023,
      rookie: false,
      brand: "Panini Donruss",
      sub_brand: "Retro",
      tags: ["Football", "49ers"],
      market_value: 12,
      image_url: null,
    },
    {
      title: "2017 Panini Prizm Patrick Mahomes Rookie",
      category_id: 1,
      status_id: 3,
      player_name: "Patrick Mahomes",
      team_name: "Kansas City Chiefs",
      year: 2017,
      rookie: true,
      brand: "Panini Prizm",
      sub_brand: "Base",
      tags: ["QB", "Rookie", "Chiefs"],
      market_value: 850,
      image_url: null,
    },
    {
      title: "2022 Panini Optic Trevor Lawrence My House",
      category_id: 1,
      status_id: 1,
      player_name: "Trevor Lawrence",
      team_name: "Jacksonville Jaguars",
      year: 2022,
      rookie: false,
      brand: "Panini Optic",
      sub_brand: "Insert",
      tags: ["QB", "Optic", "Jaguars"],
      market_value: 25,
      image_url: null,
    },
    {
      title: "2018 Panini Select Josh Allen Rookie",
      category_id: 1,
      status_id: 2,
      player_name: "Josh Allen",
      team_name: "Buffalo Bills",
      year: 2018,
      rookie: true,
      brand: "Panini Select",
      sub_brand: "Base",
      tags: ["Rookie", "Bills"],
      market_value: 240,
      image_url: null,
    },
    {
      title: "2021 Panini Donruss Justin Herbert Gold Press Proof",
      category_id: 1,
      status_id: 2,
      player_name: "Justin Herbert",
      team_name: "Los Angeles Chargers",
      year: 2021,
      rookie: false,
      brand: "Donruss",
      sub_brand: "Gold Press Proof",
      tags: ["QB", "Chargers"],
      market_value: 35,
      image_url: null,
    },
    {
      title: "2014 Topps Chrome Odell Beckham Jr. Rookie",
      category_id: 1,
      status_id: 1,
      player_name: "Odell Beckham Jr.",
      team_name: "New York Giants",
      year: 2014,
      rookie: true,
      brand: "Topps Chrome",
      sub_brand: "Base",
      tags: ["Rookie", "Giants"],
      market_value: 30,
      image_url: null,
    },

    // Baseball
    {
      title: "2011 Topps Update Mike Trout Rookie",
      category_id: 2,
      status_id: 2,
      player_name: "Mike Trout",
      team_name: "Los Angeles Angels",
      year: 2011,
      rookie: true,
      brand: "Topps Update",
      sub_brand: "Rookie Debut",
      tags: ["Rookie", "Angels"],
      market_value: 500,
      image_url: null,
    },
    {
      title: "2018 Topps Chrome Ronald Acuña Jr. Rookie",
      category_id: 2,
      status_id: 2,
      player_name: "Ronald Acuña Jr.",
      team_name: "Atlanta Braves",
      year: 2018,
      rookie: true,
      brand: "Topps Chrome",
      sub_brand: "Base",
      tags: ["Rookie", "Braves"],
      market_value: 140,
      image_url: null,
    },
    {
      title: "2019 Topps Chrome Fernando Tatis Jr. Rookie",
      category_id: 2,
      status_id: 2,
      player_name: "Fernando Tatis Jr.",
      team_name: "San Diego Padres",
      year: 2019,
      rookie: true,
      brand: "Topps Chrome",
      sub_brand: "Base Set",
      tags: ["Rookie", "Padres"],
      market_value: 90,
      image_url: null,
    },
    {
      title: "1989 Upper Deck Ken Griffey Jr. Rookie",
      category_id: 2,
      status_id: 3,
      player_name: "Ken Griffey Jr.",
      team_name: "Seattle Mariners",
      year: 1989,
      rookie: true,
      brand: "Upper Deck",
      sub_brand: "Base Set",
      tags: ["Rookie", "Mariners"],
      market_value: 250,
      image_url: null,
    },
    {
      title: "1990 Score Bo Jackson",
      category_id: 2,
      status_id: 1,
      player_name: "Bo Jackson",
      team_name: "Kansas City Royals",
      year: 1990,
      rookie: false,
      brand: "Score",
      sub_brand: "Base Set",
      tags: ["Baseball", "Royals"],
      market_value: 3,
      image_url: null,
    },
    {
      title: "2022 Bowman Chrome Julio Rodríguez Rookie",
      category_id: 2,
      status_id: 2,
      player_name: "Julio Rodríguez",
      team_name: "Seattle Mariners",
      year: 2022,
      rookie: true,
      brand: "Bowman Chrome",
      sub_brand: "Prospect",
      tags: ["Rookie", "Mariners"],
      market_value: 60,
      image_url: null,
    },
    {
      title: "2013 Topps Update Mike Trout All-Star Game",
      category_id: 2,
      status_id: 3,
      player_name: "Mike Trout",
      team_name: "Los Angeles Angels",
      year: 2013,
      rookie: false,
      brand: "Topps Update",
      sub_brand: "All-Star",
      tags: ["Baseball", "Trout"],
      market_value: 180,
      image_url: null,
    },
    {
      title: "2019 Topps Heritage Vladimir Guerrero Jr. Rookie",
      category_id: 2,
      status_id: 1,
      player_name: "Vladimir Guerrero Jr.",
      team_name: "Toronto Blue Jays",
      year: 2019,
      rookie: true,
      brand: "Topps Heritage",
      sub_brand: "Base Set",
      tags: ["Rookie", "Blue Jays"],
      market_value: 35,
      image_url: null,
    },
    {
      title: "2014 Topps Update Mookie Betts Rookie",
      category_id: 2,
      status_id: 1,
      player_name: "Mookie Betts",
      team_name: "Boston Red Sox",
      year: 2014,
      rookie: true,
      brand: "Topps Update",
      sub_brand: "Base",
      tags: ["Rookie", "Red Sox"],
      market_value: 95,
      image_url: null,
    },
    {
      title: "1993 Upper Deck Derek Jeter Rookie",
      category_id: 2,
      status_id: 3,
      player_name: "Derek Jeter",
      team_name: "New York Yankees",
      year: 1993,
      rookie: true,
      brand: "Upper Deck",
      sub_brand: "Base Set",
      tags: ["Rookie", "Yankees"],
      market_value: 300,
      image_url: null,
    },

    // Basketball
    {
      title: "2003 Topps LeBron James Rookie",
      category_id: 3,
      status_id: 3,
      player_name: "LeBron James",
      team_name: "Cleveland Cavaliers",
      year: 2003,
      rookie: true,
      brand: "Topps",
      sub_brand: "Base",
      tags: ["Rookie", "Basketball"],
      market_value: 950,
      image_url: null,
    },
    {
      title: "2018 Panini Optic Luka Dončić Rookie",
      category_id: 3,
      status_id: 2,
      player_name: "Luka Dončić",
      team_name: "Dallas Mavericks",
      year: 2018,
      rookie: true,
      brand: "Panini Optic",
      sub_brand: "Base",
      tags: ["Rookie", "Basketball"],
      market_value: 250,
      image_url: null,
    },
    {
      title: "2019-20 Panini Prizm Zion Williamson Rookie",
      category_id: 3,
      status_id: 2,
      player_name: "Zion Williamson",
      team_name: "New Orleans Pelicans",
      year: 2019,
      rookie: true,
      brand: "Panini Prizm",
      sub_brand: "Base",
      tags: ["Rookie", "Basketball"],
      market_value: 70,
      image_url: null,
    },
    {
      title: "1996 Topps Kobe Bryant Rookie",
      category_id: 3,
      status_id: 1,
      player_name: "Kobe Bryant",
      team_name: "Los Angeles Lakers",
      year: 1996,
      rookie: true,
      brand: "Topps",
      sub_brand: "Base",
      tags: ["Rookie", "Lakers"],
      market_value: 550,
      image_url: null,
    },
    {
      title: "2021 Panini Hoops Ja Morant Sky View",
      category_id: 3,
      status_id: 1,
      player_name: "Ja Morant",
      team_name: "Memphis Grizzlies",
      year: 2021,
      rookie: false,
      brand: "Panini Hoops",
      sub_brand: "Insert",
      tags: ["Insert", "Grizzlies"],
      market_value: 18,
      image_url: null,
    },
    {
      title: "2014 Panini Prizm Stephen Curry Silver",
      category_id: 3,
      status_id: 2,
      player_name: "Stephen Curry",
      team_name: "Golden State Warriors",
      year: 2014,
      rookie: false,
      brand: "Panini Prizm",
      sub_brand: "Silver Refractor",
      tags: ["Basketball", "Warriors"],
      market_value: 280,
      image_url: null,
    },
    {
      title: "2012 Panini Select Kevin Durant Silver",
      category_id: 3,
      status_id: 1,
      player_name: "Kevin Durant",
      team_name: "Oklahoma City Thunder",
      year: 2012,
      rookie: false,
      brand: "Panini Select",
      sub_brand: "Silver",
      tags: ["Basketball", "Thunder"],
      market_value: 90,
      image_url: null,
    },

    // Hockey
    {
      title: "1999 Upper Deck Wayne Gretzky Legends",
      category_id: 4,
      status_id: 1,
      player_name: "Wayne Gretzky",
      team_name: "New York Rangers",
      year: 1999,
      rookie: false,
      brand: "Upper Deck",
      sub_brand: "Legends",
      tags: ["Hockey", "Gretzky"],
      market_value: 120,
      image_url: null,
    },
    {
      title: "2016 Upper Deck Auston Matthews Young Guns Rookie",
      category_id: 4,
      status_id: 2,
      player_name: "Auston Matthews",
      team_name: "Toronto Maple Leafs",
      year: 2016,
      rookie: true,
      brand: "Upper Deck",
      sub_brand: "Young Guns",
      tags: ["Rookie", "Maple Leafs"],
      market_value: 500,
      image_url: null,
    },
  ];

  for (const card of kyleCards) {
    await createItem({ user_id: kyle.id, ...card });
  }

  console.log(`✅ Seeded ${kyleCards.length} cards for Kyle (all with placeholder images).`);
}
